dist: focal
language: python
git:
  depth: 1
matrix:
  include:
  - name: Python 2.7
    python: 2.7
  - name: Python 3.7 Deploy+Coverage
    python: 3.7
    env: DO_DELPLOY=1 CODE_COVERAGE=1
install:
- python setup.py install
- if [ "$CODE_COVERAGE" == "1" ]; then pip install coveralls codecov; fi
script:
- if [ "$CODE_COVERAGE" == "1" ]; then coverage run --source=hdlConvertorAst setup.py
  test; else python setup.py test; fi
after_success:
- coveralls
- codecov
deploy:
  provider: pypi
  user: nic30
  password:
    secure: vhOhLDJ198kU8Qoqb0MhWZk9/jeO5a4p8e+Tx71N4V/98KycZf0DSPTtX8tEirbs3XujJiEHq8ga/OpQD9SH0av/MSRGnRXQ6V8O0L6u0YB6rHc+EHk/eN8qhjBMnP/8bbKIUKQI2hM+QX4FOTLtBzPE3FWFcS9CyabIb70CtrX8FsarOuf8dxboclo8MuCKin+z8ueLUZWVqY08Jz0NwEPEQ/ZyI6IMW4wzAOKgGV/7cIpyX8nUIgpNmmFia/zzVLidorWLG22zYufYtF8LPsGLPj8ytDCj9Mlyj1MOnWED7eYArkzkxQ1NiHCn0Ch0033JPnxC0S/1T4U8AnX9jVHFcc/wV0Ap4zMgKejblFhA60e8M67OX8rE/33p5crjfCwMEywFSZVIubRwzEm+JsRZ5/dRJ4X/KuCs9A7lt6rfsmxeZFVT20azv9acNbWfcVVKfgPAceOVRaYl0WEWD0vtaO1vfAUsXqOq82FCTTkv2zMOeOLFH5rqAyaZ4vcaLBBskwRkLf09YNIsbiv+AVjxIg+4X7PYBrygnTpIUK25tfBIWZpW5Gl6kw2EU0UVJPdVTKC6GgjJFmNKDpgnWKzYdqowL9u8Tpmu/0rZZAnhbKk9Bdqrszxy0pj60I0k9stnJhz8oVDbjEXWkob4YYpFM+63XVPNWE1oPhxo9pg=
  on:
    tags: true
    branch: master
    condition: "$DO_DELPLOY = 1"
