dist: bionic
language: python

git:
  depth: 1

matrix:
  include:
    - name: "Python 2.7"
      python: 2.7           

    - name: "Python 3.7 Deploy+Coverage"
      python: 3.7           
      env: DO_DELPLOY=1 CODE_COVERAGE=1

# command to install dependencies
install:
- python setup.py install --user
- if [ "$CODE_COVERAGE" == "1" ]; then
    pip install coveralls codecov --user
 fi

script:
- if [ "$CODE_COVERAGE" == "1" ]; then
    coverage run --source=hdlConvertorAst setup.py test;
  else
    python setup.py test;
  fi

after_success:
- coveralls
- codecov

deploy:
  provider: pypi
  user: nic30
  password:
    secure: jMuoFXUX5kopaE0ezjl6NUtxAmr8SyKpRyqZQtv3TISOCCmyenqeMR3EVckEsslC5NpQOVDQHagevooo2Ysfpu6WaFll+QJgkvB7yvt3ZHNcXj9YITTpjJNmPF58jch5cjb+kFvMvPnvOnbasBtB+KRiV4tmGRXrgP0Qg7mamVnafo3Krq0OY5hAE+fK2WhFfkyZ8xdo1M794mHf9fIRcmT9c9D8cMatYjjbq724g3OJ8wlIWxDfoa012D+G2IdZOd5+aMkNMOPd504ZnUj40T39kVsgXv0kIx42Y/Wz4Om53UT2GwTBllERq4u5nDB6A4NiVTwpx4g9+r6rCjIBtX11bRgMaDCp7Jdn6KWOsKhvQtU4u2ZGUdIRCrIoJj0NInCfedKnF0FqYA4BC7HgbFCIUnpyKxR/uU0Vz7tD/jW4vP5tr4PcgQ2eTRM5eVJZ3dYoxzlFh2MzmjXA4+MamFVCRjmzDdvaBafEvYlyUUq0D2MQ2hMwjyNlcEIKW4eOi2LaVgdwJsKbDQHc66oVDQRRYu77yFW9XGhwFoTEn0km5TTVah0d9JwvqVzWo4R33FexuthR7pHQbIe7Shw6HKpV6JfbLtvYSLLBXK8UGlW7PXYQtAZN81fwZzXd+2RwCr8otJeGzNIHug0HjK4S0CYCx4HNi0qHXOl5B+DiPuw=
  on:
    tags: true
    branch: master
    condition: $DO_DELPLOY = 1
