dist: focal
language: python
git:
  depth: 1
matrix:
  include:
  - name: Python 2.7
    python: 2.7
  - name: Python 3.8 Deploy+Coverage
    python: 3.8
    env: DO_DELPLOY=1 CODE_COVERAGE=1
install:
- python setup.py install
- if [ "$CODE_COVERAGE" == "1" ]; then pip install coveralls codecov; fi
script:
- if [ "$CODE_COVERAGE" == "1" ]; then coverage run --source=hdlConvertorAst -m tests.all; else python -m tests.all; fi
after_success:
- coveralls
- codecov
deploy:
  provider: pypi
  user: nic30
  password:
    secure: YdUSwL2nVwSL2PcqSwBnuCGCa/fx2Al5VjzERG5ZVPcQqPDfw0fAOWdQpmBY9GhxO3tjoV5FNzKQ4T+LG1goVVqrXvAcg3Mje1SEI4WQi7wqay2b66Zei1snwiI1D+dqqpCgL3d0joSabbR+mJW1p9m8QAWtjv4Mgz0BHdiw9KldpTw3FfWs2F08Re0zKSlHQx7wCFXCxuEHZWaUtGLXP+ypRLgUp643NdrYX56fvTbJDtnliq8quLHlkPeqe95r6JOszQiXyXIqoZyE4jiGH0Wq6IJ7bEYOL9La/juvfQYfYKzU2IYIUObmr+IIevts4r+sT1tOQyo4OxuDRxu9wRUDVLhFa7/DOgFJga89bdMfgxqggEiCS4t0VbAcAbzsII4Fkiv25HULS3m9ITh6NZOPTrTtKBJxcw13rvdULGiZQPQ/Qy9YFG3C7aztyYLRSzY/TpQbMmv28Id1qX2s08mQ0f+yKI53WFB8ep3sKbvdEH2x/zvSJdW9nu319wQIMh/VGVIxFK807XnCV3gPCGGXuazn/ffciyeu7D4pxntDzu8tNMkkUm0dsuDpm3oWpAhX0NBP9/B7RmQDaOEjI7NGvgEQrxcxELliraYoK6Dobl1gvpk+Ks/GiCO1bY//tRgRaVr7u+P6+CgUU1G6OEKfR6gRfPxg5CY8V9C35OQ=
  on:
    tags: true
    branch: master
    condition: "$DO_DELPLOY = 1"
